name: CI - Basic Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display directory contents
        run: ls -la
